main = ".open-next/worker.js"
name = "app"
compatibility_date = "2025-10-07"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
