main = ".open-next/worker.js"
name = "portfolio"
compatibility_date = "2025-10-07"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true

[vars]
NEXT_PUBLIC_AUTH_ENDPOINT = "https://portfolio-api.roninubermensch.workers.dev/auth"
AUTH_ENDPOINT = "https://portfolio-api.roninubermensch.workers.dev/auth"
NEXT_PUBLIC_BACKEND_API_ENDPOINT = "https://portfolio-api.roninubermensch.workers.dev/api/v1"
